import { pageAbsoluteUrl } from "@/lib/site";

/** Raster OG assets under `public/og/` (generated by `npm run generate:og`). */
export const DEFAULT_OG_IMAGE_PATH = "/og/4unik-default.png";

const ROUTE_OG_BY_KEY: Record<string, string> = {
  home: "/og/4unik-home.png",
  plataforma: "/og/4unik-plataforma.png",
  "api-integracoes": "/og/4unik-api.png",
  gamificacao: "/og/4unik-gamificacao.png",
  "casos-de-uso": "/og/4unik-casos.png",
  inteligencia: "/og/4unik-inteligencia.png",
  "para-plataformas": "/og/4unik-para-plataformas.png",
  educacao: "/og/4unik-educacao.png",
  vendas: "/og/4unik-vendas.png",
  comunidades: "/og/4unik-comunidades.png",
  eventos: "/og/4unik-eventos.png",
  "gamificacao-para-rh": "/og/4unik-gamificacao.png",
};

export function resolveRouteOgImagePath(routeKey?: string): string {
  if (routeKey && ROUTE_OG_BY_KEY[routeKey]) {
    return ROUTE_OG_BY_KEY[routeKey];
  }
  return DEFAULT_OG_IMAGE_PATH;
}

export function resolveRouteOgImageUrl(routeKey?: string): string {
  return pageAbsoluteUrl(resolveRouteOgImagePath(routeKey));
}
